#
# Development docker-compose file, supporting hot-reloading
# for both frontend and backend code.
#
# The web app will be accessible at http://localhost:3000 .
#
# If the python or react packages have changed, or if you get errors
# about missing python or react packages, rebuild the containers
# with `docker-compose build`.
#
version: "3.8"
services:
  react-dev:
    container_name: react-dev-container
    image: react-dev-img:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: react-dev
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    env_file: ./frontend/.env.local
